[workspace]
authors = ["Jacob H. Rothschild"]
channels = ["conda-forge"]
name = "reimplementing"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pytorch = ">=2.6.0,<3"
pixi-pycharm = ">=0.0.8,<0.0.9"
tqdm = ">=4.67.1,<5"
torchvision = ">=0.21.0,<0.22"
matplotlib = ">=3.10.1,<4"
